### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/0.png'

### ISSUE THREAD

**Issue by bgiesing** [deeppomf/DeepCreamPy#10]
Get this on every file that has the green applied (doesn't happen on unmodified files that weren't colored like the README says to do) when running Python 3.6 with TensorFlow-GPU and CUDA on Windows 10 Pro Insider

```
PS D:\GitHub\DeepMindBreak> python decensor.py
./decensor_input/sleep.png
Vertices: 4
Rectangle detected
{'m00': 613.0, 'm10': 131795.0, 'm01': 613613.0, 'm20': 28525269.166666664, 'm11': 131924886.75, 'm02': 614232005.5, 'm30': 6214350862.5, 'm21': 28552973888.333332, 'm12': 132056060866.0, 'm03': 614857033290.5, 'mu20': 189344.16666666418, 'mu11': -1908.25, 'mu02': 5392.5, 'mu30': 1.9073486328125e-06, 'mu21': 1.2218952178955078e-06, 'mu12': 0.0, 'mu03': 0.0, 'nu20': 0.5038844786735047, 'nu11': -0.005078252862796027, 'nu02': 0.014350571760842434, 'nu30': 2.0501181762563346e-13, 'nu21': 1.3133569566642144e-13, 'nu12': 0.0, 'nu03': 0.0}
151, 937
Vertices: 4
Rectangle detected
{'m00': 445.0, 'm10': 226472.5, 'm01': 349291.0, 'm20': 115315190.0, 'm11': 177739915.41666666, 'm02': 274181328.1666666, 'm30': 58745254338.25, 'm21': 90489501412.58333, 'm12': 139501074207.08334, 'm03': 215234283644.5, 'mu20': 57227.62640449405, 'mu11': -23693.566479444504, 'mu02': 14580.568913757801, 'mu30': -4840.439407348633, 'mu21': 4451.187892101705, 'mu12': -2071.943777224049, 'mu03': 454.2616271972656, 'nu20': 0.2889919273046032, 'nu11': -0.11964936992523423, 'nu02': 0.07362994022854591, 'nu30': -0.0011587366951938292, 'nu21': 0.001065555069225811, 'nu12': -0.0004959957315865008, 'nu03': 0.00010874418050824266}
444, 720
Vertices: 4
Rectangle detected
{'m00': 543.0, 'm10': 245655.0, 'm01': 304008.1666666666, 'm20': 111252843.5, 'm11': 137530582.75, 'm02': 170209647.3333333, 'm30': 50437645477.5, 'm21': 62283505428.98333, 'm12': 76999242943.75, 'm03': 95300810358.95001, 'mu20': 117707.17403315008, 'mu11': -3719.611878424883, 'mu02': 5291.163853108883, 'mu30': -11947.300605773926, 'mu21': -3790.8630702868104, 'mu12': -759.5543276364915, 'mu03': 140.10733032226562, 'nu20': 0.3992117118699744, 'nu11': -0.012615311153929243, 'nu02': 0.01794533423246775, 'nu30': -0.0017388824212943516, 'nu21': -0.000551745149131841, 'nu12': -0.00011055013278119388, 'nu03': 2.0392068621268848e-05}
388, 495
Vertices: 4
Rectangle detected
{'m00': 476.0, 'm10': 125426.0, 'm01': 245854.0, 'm20': 33085813.333333332, 'm11': 64820472.0, 'm02': 127033436.66666666, 'm30': 8737116663.0, 'm21': 17108818547.666666, 'm12': 33512505680.666668, 'm03': 65664260612.0, 'mu20': 36062.33333333209, 'mu11': 37943.0, 'mu02': 49845.66666665673, 'mu30': 1.9073486328125e-06, 'mu21': 7.450580596923828e-09, 'mu12': 3.889203071594238e-06, 'mu03': 1.52587890625e-05, 'nu20': 0.159162194289475, 'nu11': 0.16746257326459996, 'nu02': 0.21999535108156526, 'nu30': 3.858448434538593e-13, 'nu21': 1.507206419741638e-15, 'nu12': 7.86761751105135e-13, 'nu03': 3.0867587476308745e-12}
199, 452
Traceback (most recent call last):
  File "decensor.py", line 127, in <module>
    decensor(args)
  File "decensor.py", line 53, in decensor
    (image, boxes) = find_censor_boxes(file_path)
  File "decensor.py", line 38, in find_censor_boxes
    pil_box_image = sd.cv_to_pillow(box_image)
  File "D:\GitHub\DeepMindBreak\shape_detect.py", line 34, in cv_to_pillow
    pil_box_image = Image.open(file_path).convert('RGB')
  File "C:\Python36\lib\site-packages\PIL\Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/0.png'
```

**Comment by deeppomf** [comment]
I'll look into this.

**Comment by deeppomf** [comment]
You mind privately sending the image to me via my twitter or reddit account? I can't reproduce the problem.

**Comment by Homuranana** [comment]
Hi, I had the same issue until I found the cause. shape_detect.py has the following line: `file_path = os.path.join('/tmp/', str(i) + '.png')` Because  /tmp/ only exist in Linux, it gives error in Windows. My workaround was editing it for a valid directory.

**Comment by Kadantte** [comment]
Create an Folder on the same path with shape_detect.py under name "tmp" and go to line 32 in shape_detect.py and change this line : 
    file_path = os.path.join('/tmp/', str(i) + '.png')

to this line : 
    file_path = os.path.join('./tmp', str(i) + '.png')

**Comment by deeppomf** [comment]
No longer applicable to the new version.
