### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'float'

### ISSUE THREAD

**Issue by KyouKiSu** [deeppomf/DeepCreamPy#108]
[kyoukisu DeepCreamPy-1.3.0-beta]# python3 decensor.py 
Using TensorFlow backend.
WARNING:tensorflow:From /usr/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-02-24 14:46:39.220255: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1796700000 Hz
2019-02-24 14:46:39.221066: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55d64d468470 executing computations on platform Host. Devices:
2019-02-24 14:46:39.221135: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
--------------------------------------------------------------------------
Decensoring the image ./decensor_input/mermaid_censored.png
Traceback (most recent call last):
  File "decensor.py", line 199, in <module>
    decensor.decensor_all_images_in_folder()
  File "decensor.py", line 70, in decensor_all_images_in_folder
    self.decensor_image(colored_img, colored_img, file_name)
  File "decensor.py", line 85, in decensor_image
    ori_array = image_to_array(ori)
  File "/home/kyoukisu/Downloads/DeepCreamPy-1.3.0-beta/libs/utils.py", line 7, in image_to_array
    return np.array(array / 255.0)
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'float'

**Comment by deeppomf** [comment]
Are your python libraries up to date? If you have PIL installed instead of Pillow, uninstall PIL and install Pillow.

**Comment by KyouKiSu** [comment]
I guess all python libraries are up to date. Also Pillow is installed (no PIL).
Sorry for spam.
[kyoukisu@kyoukisu DeepCreamPy-1.3.0-beta]$ sudo pip install -r requirements.txt --upgrade
Requirement already up-to-date: tensorflow in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.13.0rc2)
Requirement already up-to-date: absl-py in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.7.0)
Requirement already up-to-date: altgraph in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.16.1)
Requirement already up-to-date: astor in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.7.1)
Requirement already up-to-date: future in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.17.1)
Requirement already up-to-date: gast in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (0.2.2)
Requirement already up-to-date: grpcio in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.18.0)
Requirement already up-to-date: h5py in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.9.0)
Requirement already up-to-date: Keras in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2.2.4)
Requirement already up-to-date: Keras-Applications in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.0.7)
Requirement already up-to-date: Keras-Preprocessing in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.0.9)
Requirement already up-to-date: macholib in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.11)
Requirement already up-to-date: Markdown in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.0.1)
Requirement already up-to-date: numpy in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.16.1)
Requirement already up-to-date: pefile in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (2018.8.8)
Requirement already up-to-date: Pillow in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (5.4.1)
Requirement already up-to-date: protobuf in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (3.6.1)
Requirement already up-to-date: pywin32-ctypes in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (0.2.0)
Requirement already up-to-date: PyYAML in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (3.13)
Requirement already up-to-date: scipy in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (1.2.1)
Requirement already up-to-date: six in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 21)) (1.12.0)
Requirement already up-to-date: tensorboard in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 22)) (1.12.2)
Requirement already up-to-date: termcolor in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 23)) (1.1.0)
Requirement already up-to-date: Werkzeug in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 24)) (0.14.1)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in /usr/lib/python3.7/site-packages (from tensorflow->-r requirements.txt (line 1)) (0.33.1)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<1.14.0rc0,>=1.13.0rc0 in /usr/lib/python3.7/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.13.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3.7/site-packages (from protobuf->-r requirements.txt (line 17)) (40.6.3)
Requirement already satisfied, skipping upgrade: mock>=2.0.0 in /usr/lib/python3.7/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0rc0->tensorflow->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied, skipping upgrade: pbr>=0.11 in /usr/lib/python3.7/site-packages (from mock>=2.0.0->tensorflow-estimator<1.14.0rc0,>=1.13.0rc0->tensorflow->-r requirements.txt (line 1)) (5.1.2)
[kyoukisu@kyoukisu DeepCreamPy-1.3.0-beta]$ sudo pip install -r requirements.txt
Requirement already satisfied: tensorflow in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.13.0rc2)
Requirement already satisfied: absl-py in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: altgraph in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.16.1)
Requirement already satisfied: astor in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.7.1)
Requirement already satisfied: future in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.17.1)
Requirement already satisfied: gast in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (0.2.2)
Requirement already satisfied: grpcio in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.18.0)
Requirement already satisfied: h5py in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.9.0)
Requirement already satisfied: Keras in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2.2.4)
Requirement already satisfied: Keras-Applications in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.0.7)
Requirement already satisfied: Keras-Preprocessing in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.0.9)
Requirement already satisfied: macholib in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.11)
Requirement already satisfied: Markdown in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.0.1)
Requirement already satisfied: numpy in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.16.1)
Requirement already satisfied: pefile in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (2018.8.8)
Requirement already satisfied: Pillow in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (5.4.1)
Requirement already satisfied: protobuf in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (3.6.1)
Requirement already satisfied: pywin32-ctypes in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (0.2.0)
Requirement already satisfied: PyYAML in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (3.13)
Requirement already satisfied: scipy in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (1.2.1)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 21)) (1.12.0)
Requirement already satisfied: tensorboard in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 22)) (1.12.2)
Requirement already satisfied: termcolor in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 23)) (1.1.0)
Requirement already satisfied: Werkzeug in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 24)) (0.14.1)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3.7/site-packages (from tensorflow->-r requirements.txt (line 1)) (0.33.1)
Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0rc0 in /usr/lib/python3.7/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.13.0)
Requirement already satisfied: setuptools in /usr/lib/python3.7/site-packages (from protobuf->-r requirements.txt (line 17)) (40.6.3)
Requirement already satisfied: mock>=2.0.0 in /usr/lib/python3.7/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0rc0->tensorflow->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: pbr>=0.11 in /usr/lib/python3.7/site-packages (from mock>=2.0.0->tensorflow-estimator<1.14.0rc0,>=1.13.0rc0->tensorflow->-r requirements.txt (line 1)) (5.1.2)

**Comment by deeppomf** [comment]
Does this problem occur for all images you try?

**Comment by lightondust** [comment]
@KyouKiSu 

It seems there is a bug in pillow.

https://github.com/python-pillow/Pillow/issues/3557

install a lower version

> pip install pillow==5.3.0

or wait for version 6 release.

**Comment by KyouKiSu** [comment]
> @KyouKiSu
> 
> It seems there is a bug in pillow.
> 
> [python-pillow/Pillow#3557](https://github.com/python-pillow/Pillow/issues/3557)
> 
> install a lower version
> 
> > pip install pillow==5.3.0
> 
> or wait for version 6 release.

Thanks, got it
