### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Xeddius** [deeppomf/DeepCreamPy#114]
Using TensorFlow backend.
2019-03-29 12:33:21.167891: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "decensor.py", line 212, in <module>
    decensor = Decensor()
  File "decensor.py", line 29, in __init__
    self.load_model()
  File "decensor.py", line 42, in load_model
    lr=0.00005
  File "/home/lumine/Apps/AI/DeepCreamPy-master/libs/pconv_hybrid_model.py", line 238, in load
    self.model.load_weights(filepath)        
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/home/lumine/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/lumine/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Then exits to bash.

**Comment by Kadantte** [comment]
Download the model from https://drive.google.com/open?id=1Nzh2KAUO_rYPu2vDM_YP1EgbWtjI2hRX. Unzip the file into the /models/ folder.

**Comment by Xeddius** [comment]
Thank you!

**Comment by Kadantte** [comment]
You're welcome.

**Comment by deeppomf** [comment]
@Kadantte Thanks for explaining the issue!
