### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by r12senthil** [deeppomf/DeepCreamPy#137]
C:\Users\HI\Anaconda3>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bi
t (AMD64)] on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\HI\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\HI\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24
, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\__init__.py",
line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HI\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorf
low_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\HI\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\HI\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by deeppomf** [comment]
Your CPU isn't AVX compatible so the latest version of tensorflow can't run on your device.
Try downgrading to tensorflow 1.5
