### ISSUE TITLE
                    Using TensorFlow backend. Traceback (most recent call last):   File "decensor.py", line 198, in <module>   File "decensor.py", line 22, in __init__   File "decensor.py", line 35, in load_model   File "libs\pconv_hybrid_model.py", line 238, in load   File "site-packages\keras\engine\network.py", line 1166, in load_weights   File "site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group ValueError: You are trying to load a weight file containing 16 layers into a model with 31 layers. [2   0. Definitions.

### ISSUE THREAD

**Issue by wenshitao** [deeppomf/DeepCreamPy#145]
Using TensorFlow backend.
Traceback (most recent call last):
  File "decensor.py", line 198, in <module>
  File "decensor.py", line 22, in __init__
  File "decensor.py", line 35, in load_model
  File "libs\pconv_hybrid_model.py", line 238, in load
  File "site-packages\keras\engine\network.py", line 1166, in load_weights
  File "site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group
ValueError: You are trying to load a weight file containing 16 layers into a model with 31 layers.
[2
  0. Definitions.

**Comment by ccppoo** [comment]
don't you think is there anything wrong about this?

**Comment by deeppomf** [comment]
Is your Keras and Tensorflow up to date?

**Comment by wenshitao** [comment]
yes

**Comment by wenshitao** [comment]
i change the model
