### ISSUE TITLE
Any idea why i get this cuz DMB was working fine

### ISSUE THREAD

**Issue by Kadantte** [deeppomf/DeepCreamPy#17]
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "decensor.py", line 8, in <module>
    from libs.pconv_hybrid_model import PConvUnet
  File "C:\Users\minat\Desktop\DeepCreamPy\libs\pconv_hybrid_model.py", line 4, in <module>
    from keras.models import Model
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Kadantte** [comment]
I've python 6.7.1 64 Bits

**Comment by deeppomf** [comment]
Did this problem occur with the newest version? Do you still have the problem if you downgrade?

**Comment by deeppomf** [comment]
Have you looked at https://github.com/tensorflow/tensorflow/issues/8385?

**Comment by Kadantte** [comment]
I'll try to downgrade tensorflow and i'll see ... Nah for #8385 i'll see it right now .

**Comment by Kadantte** [comment]
Is your project need tensorflow GPU or CPU version ?! cuz i have the CPU one

**Comment by deeppomf** [comment]
Tensorflow CPU

**Comment by deeppomf** [comment]
@Kadantte Are you still experiencing the problem?

**Comment by Kadantte** [comment]
Yeah still the same and i even know what to do

**Comment by deeppomf** [comment]
Did you install https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by Kadantte** [comment]
Yep the 32 and 64 Bits
![image](https://user-images.githubusercontent.com/11579313/47603153-d63c2380-d9df-11e8-942d-5479c1863981.png)

**Comment by deeppomf** [comment]
This might be a fix on my end.
https://stackoverflow.com/questions/49732801/windows-10-pyinstaller-tensorflow-missing-modules/50580345
I will need to test it.

**Comment by Kadantte** [comment]
I tryed like everything that i found and nothing was work so the last think i have right now is formatting my Computer even if it's somehow Hard right now xD .

**Comment by Kadantte** [comment]
I open this in tensorflow repo : [#23329](https://github.com/tensorflow/tensorflow/issues/23329)

**Comment by Kadantte** [comment]
@deeppomf I fix it :D , The problem is that my CPU doesn't Support  AVX that's why i get : " ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. " So after a lot of looking for any solution but without any succeed i finally found a repo that has Tensorflow ALL version Support AVX and SSE2 Here [###](https://github.com/fo40225/tensorflow-windows-wheel) After I installed Tensorflow 1.10.0 from it it work :D .

************************

I'm testing it right know ( Deconsoring ) After it complet i'll tell ya how is it .

**Comment by Kadantte** [comment]
![image](https://user-images.githubusercontent.com/11579313/47616192-757d1b80-dab1-11e8-9340-aec766e11f63.png)

**Comment by Kadantte** [comment]
I hope that you mention that on Readme :D for anyone will have the same problem .
