### ISSUE TITLE
Mosaic Decensoring Does Not Work At All

### ISSUE THREAD

**Issue by SunstrikeHybrid** [deeppomf/DeepCreamPy#223]
Whenever I try to decensor a mosaic censored image, it just puts the exact same censored original image in the output folder without changing anything.

1. Put an edited version of the mosaic censored image in "decensor_input" and original in "decensor_input_original"
2. Open the program and choose the mosaic option.
3. Run the process.
4. The output image is the exact same as the one in "decensor_input_original"

Normally it should give me a decensored image. It doesn't.

**Installation method**
I've just downloaded the program and ran it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 64-bit
 - Supports AVX? Yes

**Comment by Kadantte** [comment]
Could please provide me with the picture you tried to decensor so I could look at it and see?

**Comment by SunstrikeHybrid** [comment]
> Could please provide me with the picture you tried to decensor so I could look at it and see?

How shall I link it? Through imgur or something?

**Comment by Kadantte** [comment]
imgur or anything u like

**Comment by Kadantte** [comment]
Well, I tried everything from releases to run the code myself and always an error! it's not just your picture it's all mosaic pictures!

v 2.2
```shell
Decensoring the image ./decensor_input/6UMoh8K.png

Corresponding original, uncolored image not found in ./decensor_input/6UMoh8K.png
Check if it exists and is in the PNG or JPG format.
```

v 1.3
```shell
Decensoring the image ./decensor_input/14.png
Traceback (most recent call last):
  File "decensor.py", line 199, in <module>
  File "decensor.py", line 67, in decensor_all_images_in_folder
UnboundLocalError: local variable 'ori_file_path' referenced before assignment
[11580] Failed to execute script decenso
```

@deeppomf u need to check this!

**Comment by SunstrikeHybrid** [comment]
Exactly, it doesn't work with any mosaic censors whatsoever...

**Comment by JensDA** [comment]
I just successfully ran through a number of mosaiced pictures on my machine with `v2.2.0-beta win64`.
Could you post your edited picture as well?

**Comment by SunstrikeHybrid** [comment]
> I just successfully ran through a number of mosaiced pictures on my machine with `v2.2.0-beta win64`.
> Could you post your edited picture as well?

Edited like highlighted in bright (255) green? I am currently not on my laptop but the edited image had all the mosaic censor covered with green with a brush with no anti-aliasing.

**Comment by SunstrikeHybrid** [comment]
Well this thread died quick.

**Comment by matt101-ctrl** [comment]
> > imgur or anything u like
> 
> https://imgur.com/a/XV0MVaM
> This should be fine (NSFW)

That's really disgusting. How can people even like this.

**Comment by SunstrikeHybrid** [comment]
> > > imgur or anything u like
> > 
> > 
> > https://imgur.com/a/XV0MVaM
> > This should be fine (NSFW)
> 
> That's really disgusting. How can people even like this.

This is how you look like rn, imagine being this pathetic you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?
![images (3)](https://user-images.githubusercontent.com/73940019/101296128-d485f080-3832-11eb-8f6b-47cb029ed7d1.png)

**Comment by matt101-ctrl** [comment]
> you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?

Anime porn is at least human...

**Comment by bmuessig** [comment]
I'm actually reasonably tolerant when it comes to other peoples sexual interests, except for minors, zoophilia, rape and death. These people can go straight to hell.

**Comment by SunstrikeHybrid** [comment]
> > you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?
> 
> Anime porn is at least human...

Lmao ok, next time think before acting like a redditor that browses r/yiffinhell

**Comment by matt101-ctrl** [comment]
> > > you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?
> > 
> > 
> > Anime porn is at least human...
> 
> Lmao ok, next time think before acting like a redditor that browses r/yiffinhell

You’re in denial.

**Comment by xstondis** [comment]
> > > > imgur or anything u like
> > > 
> > > 
> > > https://imgur.com/a/XV0MVaM
> > > This should be fine (NSFW)
> > 
> > 
> > That's really disgusting. How can people even like this.
> 
> This is how you look like rn, imagine being this pathetic you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?
> ![images (3)](https://user-images.githubusercontent.com/73940019/101296128-d485f080-3832-11eb-8f6b-47cb029ed7d1.png)

go back

> > > > imgur or anything u like
> > > 
> > > 
> > > https://imgur.com/a/XV0MVaM
> > > This should be fine (NSFW)
> > 
> > 
> > That's really disgusting. How can people even like this.
> 
> This is how you look like rn, imagine being this pathetic you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?
> ![images (3)](https://user-images.githubusercontent.com/73940019/101296128-d485f080-3832-11eb-8f6b-47cb029ed7d1.png)
go back to 4chan

**Comment by xstondis** [comment]
> > > > imgur or anything u like
> > > 
> > > 
> > > https://imgur.com/a/XV0MVaM
> > > This should be fine (NSFW)
> > 
> > 
> > That's really disgusting. How can people even like this.
> 
> This is how you look like rn, imagine being this pathetic you go around calling people who like furry porn disgusting, nobody's callin to anime porn disgusting now are we?

go back to 4chan
