### ISSUE TITLE
tensorflow error

### ISSUE THREAD

**Issue by ShinRaikdou** [deeppomf/DeepCreamPy#26]
Can't get it to work.
Installed 3.6.7 python on win7 x64
Tried both "decensor.exe" and "decensor.py" versions (after successful "pip install -r requirements.txt").
Even tried it on clean win7 x64 trough VM.
Still got that error:
`
C:\Users\Twink\Desktop\DeepCreamPy_1.2.1-beta_win64\DeepCreamPy-master>decensor.
py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper

    return importlib.import_module(mname)
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\importlib\__in
it__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper

    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\importlib\__in
it__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Twink\Desktop\DeepCreamPy_1.2.1-beta_win64\DeepCreamPy-master\d
ecensor.py", line 8, in <module>
    from libs.pconv_hybrid_model import PConvUnet
  File "C:\Users\Twink\Desktop\DeepCreamPy_1.2.1-beta_win64\DeepCreamPy-master\l
ibs\pconv_hybrid_model.py", line 4, in <module>
    from keras.models import Model
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper

    return importlib.import_module(mname)
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\importlib\__in
it__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper

    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Twink\AppData\Local\Programs\Python\Python36\lib\importlib\__in
it__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_probl
ems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

C:\Users\Twink\Desktop\DeepCreamPy_1.2.1-beta_win64\DeepCreamPy-master>`

**Comment by Kadantte** [comment]
Hi i was havcing the same problem i think ur CPU doesn't support AVX so u need to Download tensorflow from here : [LINK](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.10.0/py36/CPU/sse2) Download the 34 Bits ONE After that uninstall the one that u have and then simply install the u installed with this command from CMD : pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl

**Comment by ShinRaikdou** [comment]
@Kadantte Thank you! Works fine now.
What I did:
0) uninstalled python. Trough uninstaller and "C:\Users\***\AppData\Local\Programs\Python\Python36"
1) Installed python-3.6.7-amd64.exe
2) "pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl"
3) "pip install -r requirements.txt"
4) Thats all.

**Comment by Kadantte** [comment]
you're welcome , I'm glad it's work for you :D .
