### ISSUE TITLE
unable to open file ./models/model.h5

### ISSUE THREAD

**Issue by ckolivas** [deeppomf/DeepCreamPy#30]
Installed on ubuntu18.04 and running it from scratch with python 3.6.5 it fails due to missing this file ./models/model.h5

I tried with and without the "--is_mosaic" option (which the documentation describes both ways.)

python3 decensor.py --is_mosaic=True
Using TensorFlow backend.
Traceback (most recent call last):
  File "decensor.py", line 183, in <module>
    decensor = Decensor()
  File "decensor.py", line 22, in __init__
    self.load_model()
  File "decensor.py", line 39, in load_model
    lr=0.00005
  File "***/DeepCreamPy/libs/pconv_hybrid_model.py", line 238, in load
    self.model.load_weights(filepath)        
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by ckolivas** [comment]
My mistake. Forgot to download models.

**Comment by kingv8** [comment]
https://drive.google.com/file/d/1byrmn6wp0r27lSXcT9MC4j-RQ2R04P1Z/view

**Comment by LionnelBall** [comment]
> model.h5: https://drive.google.com/file/d/1byrmn6wp0r27lSXcT9MC4j-RQ2R04P1Z/view

Could you please upload the model file since I can't open the URL.
