### ISSUE TITLE
Release v1.2.1-beta win64 gives ModuleNotFoundError: No module named 'theano'

### ISSUE THREAD

**Issue by aH9nhP1vtwcU** [deeppomf/DeepCreamPy#46]
I get the following error when running decensor.exe from the command line.

```
>decensor.exe --is_mosaic=True
Using Theano backend.
Traceback (most recent call last):
  File "decensor.py", line 8, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "libs\pconv_hybrid_model.py", line 4, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\__init__.py", line 3, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\utils\__init__.py", line 6, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\utils\conv_utils.py", line 9, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\backend\__init__.py", line 86, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\backend\theano_backend.py", line 7, in <module>
ModuleNotFoundError: No module named 'theano'
[63848] Failed to execute script decensor

>decensor.exe
Using Theano backend.
Traceback (most recent call last):
  File "decensor.py", line 8, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "libs\pconv_hybrid_model.py", line 4, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\__init__.py", line 3, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\utils\__init__.py", line 6, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\utils\conv_utils.py", line 9, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\backend\__init__.py", line 86, in <module>
  File "c:\users\larry\desktop\venv\dcp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\keras\backend\theano_backend.py", line 7, in <module>
ModuleNotFoundError: No module named 'theano'
[42948] Failed to execute script decensor
```

This is on Windows 10 64-bit.

**Comment by deeppomf** [comment]
That's strange because Keras is configured to use Tensorflow not Theano.
Do you have Python3 and libraries like Theano installed?

**Comment by aH9nhP1vtwcU** [comment]
Yeah, that's it. I had used Keras before. Looking in "%USERPROFILE%\.keras\keras.json" I found `"backend": "theano"`. Removing the existing keras.json file resolved the issue. Thanks!
