### ISSUE TITLE
Running the binary only opens a terminal, spits out an error and closes

### ISSUE THREAD

**Issue by Kazamimi** [deeppomf/DeepCreamPy#52]
When I run the release's executable the terminal stays open for some time then quickly prints out text and closes immediately without doing anything. I took a screenshot of what I could. The directories in the log aren't mine.

![untitled](https://user-images.githubusercontent.com/24215345/47945393-03a13980-ded8-11e8-890f-a9860a25783e.png)

**Comment by hiepga9e** [comment]
![bug](https://user-images.githubusercontent.com/44720236/47949230-f8025100-df71-11e8-85a2-c4279a3391d0.png)

**Comment by Kadantte** [comment]
See this (https://github.com/deeppomf/DeepCreamPy/blob/master/INSTALLATION.md)

**Comment by llvllr30** [comment]
> See this (https://github.com/deeppomf/DeepCreamPy/blob/master/INSTALLATION.md)

so i need to install python and tensorflow ?

**Comment by haipro287** [comment]
D:\DeepCreamPy-1.2.2-beta>py decensor.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "decensor.py", line 8, in <module>
    from libs.pconv_hybrid_model import PConvUnet
  File "D:\DeepCreamPy-1.2.2-beta\libs\pconv_hybrid_model.py", line 4, in <module>
    from keras.models import Model
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\haipr\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

D:\DeepCreamPy-1.2.2-beta>


I tried to do as the same as #26 but it didn't work with me :(

**Comment by Kadantte** [comment]
@llvllr30 and @haipro287 Try ti Install [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587) After that u need ti Uninstal tensorflow and Instal it from here [Tensorflow_amd64](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.10.0/py36/CPU/sse2) u need just to open CMD from the same place where tensorflow it is and type this command pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl
Note : if u did not know how to open CMD at the same place with tensorflow u can add this at bat file : 
```
@echo off
CD /d "%~dp0"
start cmd
```

**Comment by llvllr30** [comment]
> @llvllr30 and @haipro287 Try to Install [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587) After that u need ti Uninstall tensorflow and Instal it from here [Tensorflow_amd64](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.10.0/py36/CPU/sse2) u need just to open CMD from the same place where tensorflow it is and type this command pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl
> Note : if u did not know how to open CMD at the same place with tensorflow u can add this at bat file :
> 
> ```
> @echo off
> CD /d "%~dp0"
> start cmd
> ```
i did exactly what u said and even from  [#26 (comment)](https://github.com/deeppomf/DeepCreamPy/issues/26#issuecomment-434043166)
but it still give me this error 
![image](https://user-images.githubusercontent.com/40718759/47959480-0a36ca80-e018-11e8-804e-d6a31e3a72d5.png)

**Comment by haipro287** [comment]
> @llvllr30 and @haipro287 Try to Install Microsoft Visual C++ 2015 Redistributable Update 3 After that u need ti Uninstall tensorflow and Instal it from here Tensorflow_amd64 u need just to open CMD from the same place where tensorflow it is and type this command pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl
Note : if u did not know how to open CMD at the same place with tensorflow u can add this at bat file :
@echo off
CD /d "%~dp0"
start cmd 
it worked after install Microsoft visual C++ 2015. thank you very much XD

**Comment by Kadantte** [comment]
@haipro287 you're welcome :D .
