### ISSUE TITLE
h5py error

### ISSUE THREAD

**Issue by TheMii** [deeppomf/DeepCreamPy#63]
I tried to install h5py 2.8.0 and 2.7.1. On both of them I get this error:

> $ python decensor.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "decensor.py", line 183, in <module>
    decensor = Decensor()
  File "decensor.py", line 22, in __init__
    self.load_model()
  File "decensor.py", line 39, in load_model
    lr=0.00005
  File "C:\Users\lmao\Desktop\DeepCreamPy-master\DeepCreamPy-master\downloaded\libs\pconv_hybrid_model.py", line 238, in load
    self.model.load_weights(filepath)
  File "C:\Users\lmao\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "C:\Users\lmao\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\lmao\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by Eidenz** [comment]
You need to run python from the directory where decensor.py is located. This is a typical error that occurs when you run python outside this folder.

**Comment by kiyalll** [comment]
sorry complete idiot here, how would i do that?
the easiest way i could think of was putting the contents of 'DeepCreamPy-1.2.3-beta'
into my 'Python36' folder.
this helped me a bit, i got rid of the error, but then it just stopped without error

**Comment by Eidenz** [comment]
if there wasn't any error, did you check that you put your image in the input folder in PNG format?

**Comment by kiyalll** [comment]
i did not... but now i did, and it works, thanks allot!
